server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql:///1903_dubbo?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_register_service
  registry:
    address: zookeeper://192.168.222.128:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 100000